# Generated by Django 6.0.1 on 2026-01-27 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followus',
            old_name='url',
            new_name='platform_url',
        ),
    ]
