# Generated by Django 6.0.1 on 2026-01-27 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_us', '0002_rename_url_followus_platform_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='followus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
